export const tooltipTerms: Record<string, string> = {
  Hook: "Os primeiros 3 segundos do vídeo que decidem se o espectador vai continuar assistindo ou sair.",
  "DNA Emocional": "O conjunto de emoções que dá identidade ao vídeo — o que faz ele ser único e reconhecível.",
  "Cadeia Emocional": "A sequência de emoções que o espectador sente do início ao fim do vídeo.",
  "Loop Aberto": "Uma pergunta ou situação sem resposta que faz o espectador continuar assistindo para descobrir o final.",
  "Quebra de Previsibilidade": "Um momento surpresa que o espectador não esperava, prendendo a atenção de volta.",
  "Micro-recompensas": "Pequenas satisfações ao longo do vídeo que fazem o espectador querer continuar assistindo.",
  "Ponto de Maior Tensão": "O momento mais emocionante do vídeo, onde o espectador fica mais preso na história.",
  "Emoção Central": "A emoção principal que o vídeo desperta nas pessoas e que explica por que ele viraliza.",
  "Gatilho de Ação": "O que faz o espectador tomar uma atitude após assistir — comentar, seguir ou compartilhar.",
  "Fórmula Viral": "A combinação de elementos que explica por que o vídeo se espalhou para muitas pessoas.",
  "CTA Invisível": "Um convite para agir (comentar, salvar, compartilhar) que acontece naturalmente na narrativa, sem parecer propaganda.",
  "Loop de Retenção": "Um elemento que faz o espectador assistir ao vídeo mais de uma vez.",
  "Quebra de Expectativa": "Quando o vídeo entrega algo diferente do que o espectador esperava, de forma positiva.",
  "Sinal Dominante das Métricas": "O comportamento mais frequente dos espectadores ao assistir o vídeo — o que a maioria fez depois de ver.",
  "Alerta de Replicação": "Um aviso sobre o que pode dar errado ao tentar repetir o estilo desse vídeo.",
  "Engajamento": "O total de interações que um vídeo recebe: curtidas, comentários, compartilhamentos e salvamentos.",
  Nicho: "O tema ou assunto específico que um criador de conteúdo aborda — ex: lifestyle, finanças, moda.",
  "Viralizar": "Quando um vídeo é visto e compartilhado por um número muito grande de pessoas em pouco tempo.",
  "Estrutura de Retenção": "Como o vídeo é organizado para fazer o espectador assistir até o final.",
  "Elementos Estratégicos": "Recursos usados de propósito no vídeo para aumentar visualizações, comentários e compartilhamentos.",
  "Índice de Execução": "Uma nota que indica o quão bem o vídeo foi executado tecnicamente.",
  "Probabilidade Viral": "A chance estimada de que esse vídeo seja compartilhado e alcance muitas pessoas.",
  "Potencial de Série": "Se a ideia do vídeo pode ser repetida em episódios, criando uma série de conteúdo.",
  "Motivo de Identificação": "Por que o público se identifica com a situação mostrada no vídeo.",
  "Elemento de Surpresa": "O detalhe inesperado que chama a atenção e torna o vídeo memorável.",
  "Alerta de Execução": "Um aviso prático sobre o que evitar ao gravar esse vídeo.",
  "Golden Hour": "O período logo após o nascer ou antes do pôr do sol, onde a luz natural fica mais bonita.",
  "Corte Seco": "Quando um trecho termina abruptamente e outro começa, sem transição suave.",
  "Setup": "O conjunto de equipamentos e o ambiente usado para gravar vídeos.",
  "Objetivo Emocional": "O sentimento que você quer que o espectador tenha ao terminar de assistir o vídeo.",
};
